name: linter
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.0
    - name: Run ESLint
      run: npm ci && npm run lint
